# Generated by Django 5.2.8 on 2025-11-23 16:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='A short bio about yourself', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Your profile photo', null=True, upload_to=accounts.models.user_profile_photo_path),
        ),
    ]
