# Generated by Django 5.2.8 on 2025-11-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='content_category',
            field=models.CharField(choices=[('emotions', 'भावनाहरू (Emotions)'), ('life_society', 'जीवन र समाज (Life & Society)'), ('imagination', 'कल्पना र सृजनशीलता (Imagination & Creativity)'), ('mystery_dark', 'रहस्य र गहिरा विषयहरू (Mystery & Dark Themes)'), ('patriotism_spirituality', 'देशभक्ति र आध्यात्मिकता (Patriotism & Spirituality)')], default='emotions', help_text='Content category', max_length=50),
        ),
        migrations.AlterField(
            model_name='writing',
            name='category',
            field=models.CharField(choices=[('poem', 'Poem'), ('story', 'Story')], help_text='Poem or Story', max_length=20),
        ),
    ]
